### ISSUE TITLE
stop/start of container - group 'zabbix' already exists”

### ISSUE THREAD

**Issue by jangaraj** [zabbix/zabbix-community-docker#1]
_I have a problem when i try to restart container with “docker start” after “docker stop”. I get this message : “[LOG 13:08:58] Enabling Logging and pid management. groupadd: group 'zabbix' already exists” Can you help me?
Have the same problem with groupadd on Synology Docker. Probably need to add check existing user “zabbix” to bootstrap.sh:43 (fix_permissions procedure)_

Zabbix group/user existence check will be useful.

**Comment by pozgo** [comment]
Good point, I'll add group/user check into bootstrap.sh. 

For time being remove docker image. Your data is stored in database container anyway. 
Example of my systemd service file:

```
[Unit]
Description=Zabbix Server
After=zabbix-db.service
Require=zabbix-db.service

[Service]
TimeoutStartSec=0
Restart=on-failure
RestartSec=5s
ExecStartPre=-/usr/bin/docker rm zabbix-server
ExecStart=/usr/bin/docker run \
  --name zabbix-server \
  -h zabbix.server.com \
  -p 10090:80 \
  -p 10051:10051 \
  --link=zabbix-db:zabbix.db \
  --env="DB_ADDRESS=zabbix.db" \
  --env="DB_USER=admin" \
  --env="DB_PASS=pass" \
  million12/zabbix-server
ExecStop=-/usr/bin/docker rm -f zabbix-server
ExecReload=-/usr/bin/docker restart zabbix-server
```

As you can se I do remove running container on every run. Reason being - latest version would be fetched if exists.
