### ISSUE TITLE
SERVER_PORT undefined?

### ISSUE THREAD

**Issue by nneul** [zabbix/zabbix-community-docker#102]
---
Have you read SUPPORT page?
Please read: https://github.com/monitoringartist/dockbix-xxl/blob/master/SUPPORT.md
---

^^^ Above link is not valid fyi.

### Description

Trying to stand this up pointing to an external database (non-docker) and sitting behind a proxy. It's up and running ok, but every access is producing errors from either:

include/page_header.php
or
app/views/layout.htmlpage.php

### Steps to Reproduce

1. Run the container with 

```
docker run \
	-d \
	--name zabbix \
	--log-driver="syslog" \
	-p 8081:80 \
	-p 10051:10051 \
	-v /etc/localtime:/etc/localtime:ro \
	-v /dev/log:/dev/log \
	--env="ZS_DBHost=uyyyyyyyyyyyyyyyyy" \
	--env="ZS_DBName=zabbix" \
	--env="ZS_DBUser=zabbix" \
	--env="ZS_DBPassword=xxxxxxxxxxx" \
	monitoringartist/dockbix-xxl:latest

```
Access either directly via 8081 or via proxied connection to 8081 (only exposed for testing, would normally run this at 127.0.01:8081/80).

**Expected behavior:** 
No warning message.

**Actual behavior:** 
See error/warning on top of every page. App otherwise functional.

**Reproduces how often:** 
100% of time

### Versions

Server Version: 17.09.0-ce
Kernel Version: 4.4.0-98-generic
Operating System: Ubuntu 16.04.3 LTS

### Additional Information

Any additional information, configuration, used Docker orchestration tool or
data that might be necessary to reproduce the issue.

### You Docker knowledge level

Novice docker, expert sys admin.

**Comment by jangaraj** [comment]
See https://github.com/monitoringartist/dockbix-xxl/issues/100.

**Comment by nneul** [comment]
@jangaraj I see that this isn't strictly a problem with dockbix-xxl container, but it is being aggravated/triggered by the containers nginx setup.

Any chance of having something here:

https://github.com/monitoringartist/dockbix-xxl/blob/2a1fe07dba6bd366bb02f960544d10a7ef8f9ff8/Dockerfile/dockbix-xxl/container-files-base/etc/nginx/fastcgi_params#L25

that would allow setting this if a particular env var were set?

**Comment by jangaraj** [comment]
I recommend mounting your own custom nginx conf with enabled SERVER_PORT as a workaround.
I don't like an idea of creating new env variable just to solve this issue.

Reference: https://support.zabbix.com/browse/ZBX-13044

**Comment by YouSysAdmin** [comment]
```bash
mkdir zabbix-conf
cd zabbix-conf
wget https://raw.githubusercontent.com/monitoringartist/dockbix-xxl/2a1fe07dba6bd366bb02f960544d10a7ef8f9ff8/Dockerfile/dockbix-xxl/container-files-base/etc/nginx/fastcgi_params
sed -i 's/#fastcgi_param  SERVER_PORT       $server_port;/fastcgi_param  SERVER_PORT       $server_port;/g' fastcgi_params
```
  
**add to docker-compose.yml**
`- /path/to/zabbix-conf/fastcgi_params:/etc/nginx/fastcgi_params:ro`

**Comment by nneul** [comment]
This was fixed upstream and appears to be resolved in current dev dockbix build from a few days ago.

**Comment by kujiy** [comment]
I upgraded to :latest then downgraded with just changing image :3.2.4 as you mentioned, now works fine again. I'm going to just wait for the upcoming image.
Thanks @nneul
