### ISSUE TITLE
Zabbix icmp pinger processes more than 75% busy

### ISSUE THREAD

**Issue by aferraz** [zabbix/zabbix-community-docker#109]
### Description

Zabbix icmp pinger processes more than 75% busy

### Steps to Reproduce

109 host to monitor (icmp template for all)

### Versions

Zabbix 3.4.7 Dockbix XXL

### You Docker knowledge level

Good

Hi,
 there is an ENV variable for increase number of pinging process ?

**Comment by jangaraj** [comment]
https://github.com/monitoringartist/dockbix-xxl#environmental-variables
Use environment variables to config Zabbix server and Zabbix web UI (PHP). You can add any Zabbix config variables, just add correct variable prefix (`ZS_` for Zabbix Server, `ZP_` for Zabbix Proxy) and set a variable value. Use numeric suffix (_<NUM>) for multiple config parameters. Example: you need to increase CacheSize and load two modules for Zabbix server:
```
ZS_CacheSize=50M
ZS_LoadModule_1=module1.so
ZS_LoadModule_2=module2.so
```

I don't hardcode any config variable for Zabbix.
