### ISSUE TITLE
Zabbix database should be created with utf8_bin collation

### ISSUE THREAD

**Issue by kompa3** [zabbix/zabbix-community-docker#112]
### Description

According to [Zabbix documentation](https://www.zabbix.com/documentation/3.4/manual/appendix/install/db_scripts), MySQL database should be created by utf8_bin collation.

Otherwise there will be problems with case-sensitive keys. For example, LLD may fail as reported in https://support.zabbix.com/browse/ZBX-13390.

**Comment by jangaraj** [comment]
Fixed by your PR. Thanks.
