### ISSUE TITLE
Old version of Nmap

### ISSUE THREAD

**Issue by Mentat420** [zabbix/zabbix-community-docker#118]
### Description

The version of Nmap available in the current Dockbix-xxl image is 6.40, which is over 5 years old.  Since Nmap is used for OS detection within Zabbix, it's not able to determine newer operating systems, such as Windows 2016.

### Steps to Reproduce

1. Add a Windows 2016 host to Zabbix.
2. In Zabbix on the host, select Detect Operating System

**Expected behavior:**
Nmap should recognize Windows 2016.

**Actual behavior:**
Nmap doesn't recognize the operating system.

**Reproduces how often:**
100% of the time

### Versions

Containers: 5
 Running: 5
 Paused: 0
 Stopped: 0
Images: 8
Server Version: 18.06.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 468a545b9edcd5932818eb9de8e72413e616e86e
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.15.0-34-generic
Operating System: Ubuntu 18.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.67GiB
Name: irvszabx01
ID: 4OOI:IEEM:HZPT:A7UU:CBCR:EG6W:DIDL:GWSP:JNFS:GWHQ:G7N3:HNFF
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

### Additional Information
None

### You Docker knowledge level
Moderate.

**Comment by jangaraj** [comment]
You are right, nmap is old. nmap is installed from the standard CentOS 7 repository. Currently available nmap version there is `nmap-6.40-13.el7.x86_64.rpm`. 
Unfortunately, image `monitoringartist/dockbix-xxl` is focused on the Docker monitoring and I don't see any value of keeping up to date nmap version in this image.

I recommend building own image, where you can compile latest nmap version or install newer nmap version from some 3rd party repo.
