### ISSUE TITLE
zabbix db user sets to admin

### ISSUE THREAD

**Issue by stonest** [zabbix/zabbix-community-docker#12]
Hi, 

I've set the environment variables in zabbix server for the username and password: 
ZS_DBUser=zabbix
ZS_DBPassword=password
however the zabbix server config file still has them as admin and password

**Comment by jangaraj** [comment]
Please provide more details how did you execute containers and how did you check config file.

Thx

**Comment by stonest** [comment]
my command for running zabbix server is:
ocker run -d --name zabbix-server -p 192.168.122.235:80:80 -p 192.168.122.235:443:443 -p 192.168.122.235:10051:10051 --link zabbix-db-2-4:zabbix.db -v /var/lib/container_data/zabbix-server-ssl/ssl:/etc/nginx/ssl/ --env="ZS_DBHost=zabbix.db" --env="ZS_DBUser=zabbix --env="ZS_DBPassword=*****" zabbix/zabbix-server-2.4

When I inspect the zabbix-server container I've noticed the following environment variables:
"DB_ADDRESS=127.0.0.1",
"DB_USER=admin",
"DB_PASS=password"

Are these overwriting the other variables I've set up?

**Comment by jangaraj** [comment]
You should to update your container first (docker pull ...).

DB_PASS was before, now it's ZS_DBPassword -> IMO you are using new environment variables with old image.

**Comment by stonest** [comment]
ok thanks, i will try that now

**Comment by stonest** [comment]
yep you were right, i just needed to update the image. 

Thanks!
