### ISSUE TITLE
Questions about how to replace the font

### ISSUE THREAD

**Issue by teichae** [zabbix/zabbix-community-docker#121]
### Description

Hi, I have a question.

I am Korean, and I want to change the font because there is no Hangul(Korean font) on the zabbix graph.

I don't know what it looks like to find a font file in Dockbix-xxl-4.0.

I checked only the fonts below.

"cmex10.tf cmmi10.tf cmr10.tf cmsy10.tf esint10,tf eufm10.tf msbm10.tf msbm10.tf rsfs10.tf stytf" 

Can you explain in detail how to change the font?

### Steps to Reproduce

1. docker up -d 
2. docker exec -it container id
3. ls /usr/share/fonts/lyx/
4. What should I change?

Please reply.

**Comment by jangaraj** [comment]
Fonts used by Zabbix graphs are stored in `/usr/local/src/zabbix/frontends/php/fonts`:
```
$ docker exec -ti dockbix ls -lah /usr/local/src/zabbix/frontends/php/fonts
total 6.7M
drwxr-xr-x.  2 zabbix zabbix   45 Oct 30 10:39 .
drwxr-xr-x. 19 zabbix zabbix 4.0K Dec 22 09:08 ..
-rw-r--r--.  1 zabbix zabbix 739K Oct 30 10:35 DejaVuSans.ttf
-rw-r--r--.  1 zabbix zabbix 6.0M Oct 30 10:39 ipagp.ttf
```
Font name configuration is stored in `defines.inc.php` controlled by env variable `ZBX_GRAPH_FONT_NAME`:
```
$ docker exec -ti dockbix cat /usr/local/src/zabbix/frontends/php/include/defines.inc.php | grep ZBX_GRAPH_FONT_NAME
define('ZBX_GRAPH_FONT_NAME',           'DejaVuSans'); // font file name
```

So mount your ttf Korean fonts (with proper read permissions) and configure it via env variable:

docker run -d --name dockbix \\
    ...
   **-v /host-folder-with-korean-ttf-font/korean-font.ttf:/usr/local/src/zabbix/frontends/php/fonts/korean-font.ttf
   -e ZBX_GRAPH_FONT_NAME=korean-font** \\
    monitoringartist/dockbix-xxl:latest

Please use https://www.zabbix.org/wiki/Getting_help for any further help, because this is request for Zabbix support, which is really not in the scope of this project.

Thx.

**Comment by teichae** [comment]
> Fonts used by Zabbix graphs are stored in `/usr/local/src/zabbix/frontends/php/fonts`:
> 
> ```
> $ docker exec -ti dockbix ls -lah /usr/local/src/zabbix/frontends/php/fonts
> total 6.7M
> drwxr-xr-x.  2 zabbix zabbix   45 Oct 30 10:39 .
> drwxr-xr-x. 19 zabbix zabbix 4.0K Dec 22 09:08 ..
> -rw-r--r--.  1 zabbix zabbix 739K Oct 30 10:35 DejaVuSans.ttf
> -rw-r--r--.  1 zabbix zabbix 6.0M Oct 30 10:39 ipagp.ttf
> ```
> Font name configuration is stored in `defines.inc.php` controlled by env variable `ZBX_GRAPH_FONT_NAME`:
> 
> ```
> $ docker exec -ti dockbix cat /usr/local/src/zabbix/frontends/php/include/defines.inc.php | grep ZBX_GRAPH_FONT_NAME
> define('ZBX_GRAPH_FONT_NAME',           'DejaVuSans'); // font file name
> ```
> So mount your ttf Korean fonts (with proper read permissions) and configure it via env variable:
> 
> docker run -d --name dockbix \
> ...
> **-v /host-folder-with-korean-ttf-font/korean-font.ttf:/usr/local/src/zabbix/frontends/php/fonts/korean-font.ttf -e ZBX_GRAPH_FONT_NAME=korean-font** \
> monitoringartist/dockbix-xxl:latest
> Please use https://www.zabbix.org/wiki/Getting_help for any further help, because this is request for Zabbix support, which is really not in the scope of this project.
> 
> Thx.

Hi @jangaraj 

Thank you for your good answer.

I checked the font files on the route you showed me.

Since Koreans can see this solution, I'm going to write down an easy one.
(Actually, the font problem is a frequent problem for Koreans who use Zabbix.)

1. Please Korea font download (ex malgun, batang, gulim)
2. Font rename -> DejaVuSans.ttf
3. Docker cp DejaVuSans.ttf ContainerID:/usr/local/src/zabbix/frontends/php/fonts
4. Docker-compose restart
5. Resolved

**Comment by jangaraj** [comment]
Do you have any recommendation for a good free Korean font for graphs (https://www.freekoreanfont.com/)? I may add it to the image. There is already ipagp.ttf (Japanese font).

**Comment by teichae** [comment]
> Do you have any recommendation for a good free Korean font for graphs (https://www.freekoreanfont.com/)? I may add it to the image. There is already ipagp.ttf (Japanese font).

Oh, thank you for your feedback.

I recommend Malgun.ttf

Go to the link below to download it from the official MS website.

https://www.microsoft.com/en-us/download/confirmation.aspx?id=10490

After uncompressing VistaFont.exe, use only Malgun.ttf.

Thanks to your kindness, I feel good at using this dockbix-xxl.

Let me introduce Dockbix-xxl to the local Zabbix community channel in Korea.

Thank you.

**Comment by jangaraj** [comment]
> I recommend Malgun.ttf
> Go to the link below to download it from the official MS website.
> https://www.microsoft.com/en-us/download/confirmation.aspx?id=10490

Unfortunately, this is not a good one, because of the licence.

**Comment by teichae** [comment]
> > I recommend Malgun.ttf
> > Go to the link below to download it from the official MS website.
> > https://www.microsoft.com/en-us/download/confirmation.aspx?id=10490
> 
> Unfortunately, this is not a good one, because of the licence.

Doesn't it look like a free license when I check the license for this?

I may have misunderstood because I am not good at English.

Please check.

https://www.freekoreanfont.com/malgun-gothic-download/

Permission
Free for personal and commercial projects

If it still matters, I will check for other free fonts.

**Comment by jangaraj** [comment]
> https://www.freekoreanfont.com/malgun-gothic-download/

Yes, but final download URL is again https://www.microsoft.com/en-us/download/confirmation.aspx?id=10490, where is MS licence:
![image](https://user-images.githubusercontent.com/1182932/50376929-cd994f80-0614-11e9-870d-25ac327eb955.png)

**Comment by teichae** [comment]
> > https://www.freekoreanfont.com/malgun-gothic-download/
> 
> Yes, but final download URL is again https://www.microsoft.com/en-us/download/confirmation.aspx?id=10490, where is MS licence:
> ![image](https://user-images.githubusercontent.com/1182932/50376929-cd994f80-0614-11e9-870d-25ac327eb955.png)

Oh, I didn't know.

Thank you for the details.

I'm going to look for another font, and it takes a little time since I need to make sure the output is good after applying the font.

Thank you.

**Comment by teichae** [comment]
> > https://www.freekoreanfont.com/malgun-gothic-download/
> 
> Yes, but final download URL is again https://www.microsoft.com/en-us/download/confirmation.aspx?id=10490, where is MS licence:
> ![image](https://user-images.githubusercontent.com/1182932/50376929-cd994f80-0614-11e9-870d-25ac327eb955.png)

I fount it.

The following font has the regulations for open-font licenses, and redistribution is also found to be OK.

And I've done a check to see if the output on the graph is OK.

https://fonts.google.com/specimen/Noto+Sans+KR

I hope this will help.

Thank you.
