### ISSUE TITLE
Lack of free swap space on Zabbix server

### ISSUE THREAD

**Issue by Xbirdfr** [zabbix/zabbix-community-docker#123]
### Description
Zabbix find an issue : Lack of free swap space on Zabbix server
I don't know how to fix it, as the server is inside a docker container

### Steps to Reproduce

Fresh install and first start

### Versions

monitoringartist/zabbix-db-mariadb latest
monitoringartist/zabbix-xxl latest

### Additional Information

Docker command lines used : 

`docker run -d --name zabbix -p 9080:80 -p 10051:10051 -v /etc/localtime:/etc/localtime:ro --link zabbix-db:zabbix.db --env="ZS_DBHost=zabbix.db" --env="ZS_DBUser=zabbix" --env="ZS_DBPassword=THE_PASSWORD" --env="XXL_zapix=true" --env="XXL_grapher=true" monitoringartist/zabbix-xxl:latest`

`docker run -d --name zabbix-db --env="MARIADB_USER=zabbix" --env="MARIADB_PASS=THE_PASSWORD" monitoringartist/zabbix-db-mariadb`

### You Docker knowledge level

Medium

Thanks

**Comment by jangaraj** [comment]
That alert is probably coming from default Linux template. You should to disable that trigger. Please use https://www.zabbix.org/wiki/Getting_help to get help with Zabbix configuration.
