### ISSUE TITLE
ICMP fping

### ISSUE THREAD

**Issue by ivan-mezentsev** [zabbix/zabbix-community-docker#14]
Need to fix:

docker exec zabbix-server chown root:zabbix /usr/local/sbin/fping
docker exec zabbix-server chmod 4710 /usr/local/sbin/fping

**Comment by jangaraj** [comment]
Thank you Ivan,

Dockerfile updated:

```
  setcap cap_net_raw+ep /usr/local/sbin/fping || echo 'Warning: setcap cap_net_raw+ep /usr/local/sbin/fping' && \
  setcap cap_net_raw+ep /usr/local/sbin/fping6 || echo 'Warning: setcap cap_net_raw+ep /usr/local/sbin/fping6' && \
  chmod 4710 /usr/local/sbin/fping && \
  chmod 4710 /usr/local/sbin/fping6 && \
```
- boostrap.sh

```
  chown root:zabbix /usr/local/sbin/fping
  chown root:zabbix /usr/local/sbin/fping6
```

Repo retagged, automated build in progress ....

**Comment by TitinDev** [comment]
Fping not installed on : Docker image zabbix-server-3.0

**Comment by jangaraj** [comment]
It's there:

```
docker run --rm zabbix/zabbix-server-3.0:dev whereis fping
fping: /usr/sbin/fping /usr/share/man/man8/fping6.8 /usr/share/man/man8/fping.8
```

**Comment by TitinDev** [comment]
I fixed with: yum install fping

**Comment by jangaraj** [comment]
You must have some too old image. Fping is definitely there.

**Comment by TitinDev** [comment]
deployment time of 2 days, there problem at compile time, I have nothing in /usr/sbin/fping
