### ISSUE TITLE
Unable to execute fping as the zabbix user

### ISSUE THREAD

**Issue by rlopezro** [zabbix/zabbix-community-docker#16]
Hi,

I am using `zabbix/zabbix-server-2.4:2.4.7`. When using the  `Template ICMP Ping` template the following error showed up:

<img width="1440" alt="screen shot 2015-12-05 at 8 47 19 pm" src="https://cloud.githubusercontent.com/assets/15841313/11611750/92d3e0c6-9b92-11e5-8009-b8b3bca75eca.png">

It seems like the zabbix user was not able to run fping and fping6. I fixed this by running:

```
chmod ug+s /usr/sbin/fping
chmod ug+s /usr/sbin/fping6
```

Could this be added to the Dockerfile?

Thanks!

**Comment by jangaraj** [comment]
Permissions for fping are pain :-) 

Some chmod is already there https://github.com/zabbix/zabbix-community-docker/blob/master/Dockerfile/zabbix-server-2.4/Dockerfile#L149. Could you test your chmod in Dockerfile please? When you acknowledge it, then I'll be happy to add it to dockerfile.

Thx

**Comment by rlopezro** [comment]
Sorry, I was wrong. The Dockerfile looks good. The chmod on the Dockerfile sets the correct permissions, but the `setuid` permissions are cleared when the following `chown` commands in `bootstrap.sh` are executed (https://github.com/zabbix/zabbix-community-docker/blob/master/Dockerfile/zabbix-server-2.4/container-files-zabbix/config/init/bootstrap.sh#L51,L52):

```
chown root:zabbix /usr/sbin/fping
chown root:zabbix /usr/sbin/fping6
```

Before running `bootstrap.sh`:

```
[root@97abb4d229c4 /]# ls -lart /usr/sbin/fping*
-rws--x--- 1 root root 90436 Nov 21 19:28 /usr/sbin/fping6
-rws--x--- 1 root root 89943 Nov 21 19:28 /usr/sbin/fping
```

After running `bootstrap.sh`:

```
[root@1d3fd1afba48 /]# ls -lart /usr/sbin/fping*
-rwx--x--- 1 root zabbix 90436 Nov 21 19:28 /usr/sbin/fping6
-rwx--x--- 1 root zabbix 89943 Nov 21 19:28 /usr/sbin/fping
```

This `chown` behavior is by design: http://unix.stackexchange.com/questions/53665/chown-removes-sticky-bit-bug-or-feature

I tested adding the `chmod` commands in `bootstrap.sh` after running `chown` and everything worked as expected. This is what I ended up with:

```
chown root:zabbix /usr/sbin/fping
chown root:zabbix /usr/sbin/fping6
chmod 4710 /usr/sbin/fping
chmod 4710 /usr/sbin/fping6
```

Thanks!

**Comment by jangaraj** [comment]
Perfect, mystery has been solved. I've updated master branch - :latest docker image. I'll retag and rebuild rest of versions later.

Thank you for your help.

**Comment by rlopezro** [comment]
Awesome! No problem!

**Comment by jangaraj** [comment]
Done, Docker images have been rebuilt.

**Comment by jangaraj** [comment]
TODO: retest

**Comment by jangaraj** [comment]
Fixed (again).

**Comment by mapsrof** [comment]
Having same problem with zabbix-proxy-sqlite3 on docker (latest release)...
