### ISSUE TITLE
UI Language can be selected English only @zabbix/zabbix-server-2.4:2.4.6

### ISSUE THREAD

**Issue by xiaoping378** [zabbix/zabbix-community-docker#19]
Can't upload screenshot....
when configure user, can't select language.

**Comment by jangaraj** [comment]
Pls use some 3rd party site for your screenshot.

**Comment by xiaoping378** [comment]
@jangaraj 
[The link](http://pan.baidu.com/s/1gdZ3RIN)

**Comment by jangaraj** [comment]
It's OK. Which version do you see in the bottom? Docker image zabbix/zabbix-server-2.4:2.4.6:

![capture](https://cloud.githubusercontent.com/assets/1182932/12050128/b2d91e24-aef0-11e5-8322-0b4978e647d2.PNG)

**Comment by xiaoping378** [comment]
Yes, i am using zabbix/zabbix-server-2.4:2.4.6
run 'locale -a', just show 

``` bash
[root@zabbix-server /]# locale -a
C
en_US.utf8
POSIX
```

Maybe i need update the images....

**Comment by jangaraj** [comment]
Yes, pls update your image. The latest docker build (2015-12-21) doesn't have this issue.
