### ISSUE TITLE
add postgresql support for zabbix 3.0

### ISSUE THREAD

**Issue by itatabitovski** [zabbix/zabbix-community-docker#25]
Could you please add postgresql support to zabbix 3.0?

**Comment by jangaraj** [comment]
Yes. It's in my TODO, but unfortunately my  time is limited. Will be awesome if you can create PR. You will need to: 
- add postgresql libs + compile everything again => 2 zabix_server binaries will be in the docker image and then some environment variable (eg `ZS_DBEngine` default = mysql) will start the zabbix server with selected DB support
- update bootstrap.sh, so postgresql SQL willl be imported automatically
  Probably zabbix-db-postresql image will be useful as well (I have seen some in Github).

**Comment by itatabitovski** [comment]
@jangaraj why would you need 2 zabbix_server binaries? isn't it just adding --with-psql in the configure enough?

**Comment by jangaraj** [comment]
I really don't want to manage many Docker images. I would like to have only one common image and then user will specify, what should be executed in the container. Zenoss is also following this concept - they have many "monitoring microservices" in one Docker image.
I know it's not really proper microservice Docker concept, but unfortunately Zabbix is not designated to be microservice. If I create psql version for server, then also web/proxy/agent should have their psql Dockerfile version -> I don't want to manage for example 10 Zabbix Docker images atm.

BTW: you still can't compile --with-mysql --with-postgresql: `configure: error: You can configure for only one database.` - I was trying it also in 2.4 ages ago.

**Comment by luchnck** [comment]
Postgresql support added in my fork,  [luchnck/zabbix-xxl-postgresql](https://github.com/luchnck/zabbix-xxl-postgresql/tree/master/Dockerfile/zabbix-xxl). I tried to follow Your recommendations in part of "zabbix_server binary for each type db in one image" for multibase support (depends on $DB_engine env variable), now is available basic usage with external pgsql db (such as start container with link on external DB, init zbx server/proxy database if not exist), there is no specialized image for postgresql db, but I built and tested it with [hasufell/gentoo-postgresql](https://hub.docker.com/r/hasufell/gentoo-postgresql/) image,if its ok, i think that'll needs to optimize it for zbx needs in future.

**Comment by jangaraj** [comment]
@luchnck 👍 I'm watching your repo. Do you want to keep that postgresql fork in your repo?

**Comment by luchnck** [comment]
Yes, but if it can be usable for project, we can merge it

**Comment by jangaraj** [comment]
Unfortunately, PostgreSQL version is not an easy task, due to direct SQL support. Link to https://github.com/luchnck/zabbix-xxl-postgresql has been added into README.
