### ISSUE TITLE
Add localtime 

### ISSUE THREAD

**Issue by daviddelon** [zabbix/zabbix-community-docker#29]
I think docker-compose.yml and documentation should contain an instruction to synchronize timezone from the host with docker.
For docker-compose : 
zabbix:
 (other stuff ...)
  volumes:
    - /etc/localtime:/etc/localtime:ro

and for starting zabbix with docker 
run -v /etc/localtime:/etc/localtime:ro  and other required parameters.

**Comment by jangaraj** [comment]
Done. Thank you David.
