### ISSUE TITLE
Split into various service containers and link to each other

### ISSUE THREAD

**Issue by endersonmaia** [zabbix/zabbix-community-docker#3]
Why don't have each service in a separate container ?

Ex.:
- [ ] zabbix-web  - just nginx and php-fpm and zabbix-web
- [ ] zabbix-server - just the server, could use some minimal image, like alpine
- [ ] zabbix-agent - using `--privileged` and mapping local files via `-v` could be used to monitor the host
- [ ] zabbix-server-jmx (maybe even split an `--enable-java` docker image, for have

All images prepared to receive environment variables to connect to other services/containers and have config files replaced.

I have https://github.com/endersonmaia/docker-zabbix-server and https://github.com/endersonmaia/docker-zabbix-web, but are not updated. 

Maybe I'll make a PR to some of the topics above.

**Comment by jangaraj** [comment]
Hi Enderson,
If you have good idea, we don't stop you :-) It makes sense from microservice point of view.
Let's discuss your ideas on Zabbix forum first - https://www.zabbix.com/forum/showthread.php?t=49520

**Comment by pozgo** [comment]
This might be of help. [Docker Misconceptions](https://valdhaus.co/writings/docker-misconceptions/).
One of the pints speaks about similar subject. 

> **Misconception:**
>    **You should have only one process per Docker container!**
>    It's important to understand that it is far simpler to manage Docker if you view it as role-based virtual    machine rather than as deployable single-purpose processes. For example, you'd build an 'app' container    that is very similar to an 'app' VM you'd create along with the init, cron, ssh, etc processes within it. Don't try to capture every process in its own container with a separate container for ssh, cron, app, web server, etc.
>    There are great theoretical arguments for having a process per container, but in practice, it's a bit of a nightmare to actually manage. Perhaps at extremely large scales that approach makes more sense, but for most systems, you'll want role-based containers (app, db, redis, etc).

**Comment by jangaraj** [comment]
I'm closing as wontfix for now. It's not a problem to update Dockerfile and split Zabbix into smaller parts for Docker pro users. However it'll be painful for normal users  to start X containers only one Zabbix service.
