### ISSUE TITLE
Custom config issue

### ISSUE THREAD

**Issue by loderunner84** [zabbix/zabbix-community-docker#32]
if [ -f /etc/custom-config/zabbix_server.conf ]; then
  FZS_DBPassword=$(grep ^DBPassword= /etc/custom-config/zabbix_server.conf | awk -F= '{print $2}')
  if [ ! -z "$VAR" ]; then

why VAR?
it stoping then cuscom config loaded

**Comment by jangaraj** [comment]
Because nobody is perfect :-) I'll fix this problem. Thank you for your report.

**Comment by loderunner84** [comment]
Thank you for your work!

**Comment by jangaraj** [comment]
Still not fixed - I'm keeping it opened.

**Comment by jangaraj** [comment]
Done. Docker images were updated. Let me know, if you find another problem. Thank you.
