### ISSUE TITLE
ZA config issue

### ISSUE THREAD

**Issue by loderunner84** [zabbix/zabbix-community-docker#34]
then I add some like ZA_Include=/usr/local/etc/zabbix_agentd.conf.d/*.conf and first start of container looks fine. then I restart container zabbix agent did not start. open zabbix_agentd.conf and see this:

```
### Option: TLSPSKFile
#       Full pathname of a file containing the pre-shared key.
#
# Mandatory: no
# Default:
# TLSPSKFile=
Hostname=Zabbix server

Include=/usr/local/etc/zabbix_agentd.conf.d/*.conf
Hostname=Zabbix server
Include=/usr/local/etc/zabbix_agentd.conf.d/*.conf
Hostname=Zabbix server
```

userparameters of ZA is duplicated by that config

**Comment by jangaraj** [comment]
Please provise more details, so I'll be able replicate your problem:
- How did you start container?
- How did you restart container?
- Zabbix-server version (from command line)

Jan Garaj

Email/IM: jan.garaj@gmail.com
   Mobile: +44 79 234 69004 (+421 949 113 911)
     Web: http://www.jangaraj.com
LinkedIn: http://www.linkedin.com/in/jangaraj

**Comment by loderunner84** [comment]
```
[root@zabbix /]# zabbix_server --version
zabbix_server (Zabbix) 3.0.1 (2016-03-16)
Revision {ZABBIX_REVISION} 26 February 2016, compilation time: Mar 16 2016 02:36:32

Copyright (C) 2016 Zabbix SIA
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it according to
the license. There is NO WARRANTY, to the extent permitted by law.

```

start and restart by docker web gui of synology nas)

**Comment by jangaraj** [comment]
OK, who want to send me Synology for testing? :-D
Any printscreens pls?

**Comment by loderunner84** [comment]
![004](https://cloud.githubusercontent.com/assets/13444963/13805577/1b998e82-eb80-11e5-818e-57caf5c3f549.png)

**Comment by jangaraj** [comment]
Please pull latest docker image and test your use case. Hopefully it's fixed.

**Comment by loderunner84** [comment]
I'm newbe in docker. Can i start my container with new pulled image or create new anyway?

**Comment by jangaraj** [comment]
No, you have to create new one. Docker container is instance of Docker image.

**Comment by loderunner84** [comment]
yep.. no dups in config now

**Comment by jangaraj** [comment]
Great, I'm closing issue. BTW: could you reupload printscreen, but set up English in your UI please.

**Comment by loderunner84** [comment]
![005](https://cloud.githubusercontent.com/assets/13444963/13842975/ac5b7758-ec63-11e5-8734-71fd9de7bbda.png)

**Comment by jangaraj** [comment]
Thx - http://zabbix.org/wiki/Dockerized_Zabbix#Use_cases
