### ISSUE TITLE
Fping request

### ISSUE THREAD

**Issue by chernogorsky** [zabbix/zabbix-community-docker#4]
Please add fping to main zabbix images

This can be easily done by custom Dockerfile, but i suppose, that this is general use feature

cat << EOT | tee Dockerfile

```
FROM zabbix/zabbix-server-2.4:latest

RUN yum -y install fping
COPY container-files /
```

EOT

mkdir -p container-files/config/init/
more container-files/config/init/zz-fping-permissions.sh 

```
#!/bin/sh
set -eu
export TERM=xterm
# Bash Colors
red=`tput setaf 1`
green=`tput setaf 2`
yellow=`tput setaf 3`
white=`tput setaf 7`
bold=`tput bold`
reset=`tput sgr0`
separator=$(echo && printf '=%.0s' {1..100} && echo)
# Logging Finctions
log() {
  if [[ "$@" ]]; then echo "${bold}${green}[LOG `date +'%T'`]${reset} $@";
  else echo; fi
}
warning() {
  echo "${bold}${yellow}[WARNING `date +'%T'`]${reset} ${yellow}$@${reset}";
}
error() {
  echo "${bold}${red}[ERROR `date +'%T'`]${reset} ${red}$@${reset}";
}

log "Fix fping permissions"
chown root:zabbix /usr/sbin/fping && \
chmod 710 /usr/sbin/fping && \
chmod ug+s /usr/sbin/fping
log "Done
```

or add to init/bootstrap.sh into
fix_permissions() {

**Comment by pozgo** [comment]
Hi Chernogorsky,

Before that please discuss it on Zabbix forum [here](https://www.zabbix.com/forum/showthread.php?t=49520) if more people agree to have it in base image.  
After that feel free to send us PR and we can merge it. 

PS. I have my own customised Docker image that is using official image as base layer. Have a look [here](https://github.com/million12/docker-zabbix-server). I think you could do it the same way and just add whatever you want to.

**Comment by chernogorsky** [comment]
Thanks, I`ll write.
I have already created image for myself.
And fping is a standart application to any icmp agent operations, but ok, i understand, forum.

**Comment by jangaraj** [comment]
/usr/sbin/fping and /usr/sbin/fping6 added
