### ISSUE TITLE
Should enable include directories for easier customization

### ISSUE THREAD

**Issue by jquacinella** [zabbix/zabbix-community-docker#42]
The default zabbix config file keeps the Include directive commented out. Uncommenting it to allow /usr/local/etc/zabbix_server.conf.d/*conf file would help users customize the setup. Also, if you can enable the Java Gateway, you should have StartJavaPollers to a non-zero value by default

**Comment by jquacinella** [comment]
Nevermind, I see a ZS_Include option

**Comment by jquacinella** [comment]
Actually keeping this open, doesnt seem to be configurable at runtime but only at build time.

**Comment by jangaraj** [comment]
Runtime config is OK, I don't see any problem:

```
[root@dockerhost ~]# docker run \
>     -d \
>     --name zabbix \
>     -p 80:80 \
>     -p 10051:10051 \
>     -v /etc/localtime:/etc/localtime:ro \
>     --link zabbix-db:zabbix.db \
>     --env="ZS_DBHost=zabbix.db" \
>     --env="ZS_DBUser=zabbix" \
>     --env="ZS_DBPassword=my_password" \
>     --env="ZS_Include=/mypath" \
>      zabbix/zabbix-3.0:latest
ea8e9c8eeac436ac6aea34cf55b48ac46f0d037b313ac24e5f7089b8c37e94fc
[root@dockerhost ~]# docker exec -ti zabbix  grep Include /usr/local/etc/zabbix_server.conf
### Option: Include
# Include=
# Include=/usr/local/etc/zabbix_server.general.conf
# Include=/usr/local/etc/zabbix_server.conf.d/
# Include=/usr/local/etc/zabbix_server.conf.d/*.conf
### Include=ZS_Include
Include=/mypath
```

> Also, if you can enable the Java Gateway, you should have StartJavaPollers to a non-zero value by default

Yes I can, but I don't know how many java pollers should be started -> IMO it's user responsibility to configure it.

**Comment by jquacinella** [comment]
Should have waited until opening the tix, looks like I had an issue with my compose file. Anyways, thanks for a great product

**Comment by jangaraj** [comment]
No problem. Ywc.
