### ISSUE TITLE
How to restore 

### ISSUE THREAD

**Issue by kujiy** [zabbix/zabbix-community-docker#44]
Hi. Thank you for sharing your great project.

I lost our zabbix settings. I have the following backup files but I don't know how to restore with them.

```
root@sv:/# cd /backups/
root@sv:/backups# ll
-rw-r--r--  1 root root 1.1M 2016-05-31 13:49:13 zabbix_cfg_localhost_20160531-1349_db-3.0.0.sql.gz
-rw-r--r--  1 root root 8.1M 2016-05-31 13:49:16 zabbix_db_dump_2016-05-31-13.49.13.sql.bz2
```

Does anyone tell me that?

**Comment by kujiy** [comment]
I was succeeded to restore with the backups. But I don't know this is the right way.

``` sh
# cp backup file
$ cp /backups/zabbix_db_dump_2016-05-31-13.49.13.sql.bz2 .
# Extract it
$ bunzip2 zabbix_db_dump_2016-05-31-13.49.13.sql.bz2 
# Manual import
$ docker exec -i zabbix-db mysql -uzabbix -p --password=my_password zabbix < zabbix_db_dump_2016-05-31-13.49.13.sql
```

**Comment by jangaraj** [comment]
How to backup/restore DB is not in the scope of this project. Instructions are provided as a example. You can still use different methods/tools. I will add example of backup restore later:

```
# remove zabbix server container
docker rm -f zabbix

# restore old data (all current data will be dropped!!!) you can extract file to stdout and then import
docker exec -i zabbix-db sh -c 'bunzip2 -dc /backups/zabbix_db_dump_2016-05-25-02.57.46.sql.bz2 | mysql -uzabbix -p --password=my_password zabbix'

# run zabbix server again
docker run ...
```

You can use gzip, tar, ... utilities. You have /backups volume, so you can still use utilities also from your docker host -> #45 is not the the best practice from this point of view.

**Comment by kujiy** [comment]
Thanks for your answer. I completely understood and learned lots of things about this case. And I'm glad that you used my `docker exec` command in your example. How about adding your example in the readme with marked "just for an example" notes?

**Comment by jangaraj** [comment]
Done. It's in xxl branch for now. I'm going to merge xxl branch soon.
