### ISSUE TITLE
DNS settings

### ISSUE THREAD

**Issue by samirfor** [zabbix/zabbix-community-docker#46]
`Couldn't connect to server: Failed connect to myintranetdomain:80; No route to host`

**myintranetdomain** is an internal and resolvable domain only by our own DNS server.

How can I change DNS settings?

**Comment by samirfor** [comment]
Thanks to `docker exec -ti zabbix /bin/bash` I could do this by editting the file **/etc/resolv.conf**

Default is:

```
nameserver 8.8.8.8
nameserver 8.8.4.4
```

**Comment by jangaraj** [comment]
That's not correct approach - https://docs.docker.com/engine/userguide/networking/default_network/configure-dns/
