### ISSUE TITLE
Can't select to link templates in the host page

### ISSUE THREAD

**Issue by xiaoping378** [zabbix/zabbix-community-docker#48]
![](http://imglf0.nosdn.127.net/img/THFYV1NrZkw4R01Ya0d2cU4xN2tLR3lHU1kyYWtHN0JMTG9lYjMyQ2xmOTdTVWVmMmdjOGh3PT0.png?imageView&thumbnail=1731y448&type=jpg&quality=96&stripmeta=0&type=jpg)
I am using 3.0.3  and found can't add link the templates in the host page

**Comment by jangaraj** [comment]
It's not problem related to dockerized zabbix. It's Zabbix issue - https://support.zabbix.com/browse/ZBX-10840.

**Comment by xiaoping378** [comment]
Thanks, Got it.
