### ISSUE TITLE
No route to host from zabbix-server container to docker host

### ISSUE THREAD

**Issue by Jacq** [zabbix/zabbix-community-docker#50]
Hi,
I've tried to add the docker host as a linux host to be monitored by zabbix but I get "no route to host",
The host docker0 bridge ip is: 172.18.0.1
The zabbix container ip is: 172.18.0.2
Executing in host "telnet 172.18.0.1 10050" allows connection.
Executing in zabbix container "telnet 172.18.0.2 10050" outputs "no route to host".
However I can ssh from container to host normally "ssh 172.18.0.2".
Host firewall is disabled but I couldn't check zabbix container firewall due to error "Failed to get D-Bus connection: Operation not permitted" when running systemctl related commands.
What I'm missing?
Cheers,
Jacq

**Comment by jangaraj** [comment]
It doesn't look like a Zabbix container issue. Configure your Docker networking properly https://docs.docker.com/engine/userguide/networking/ or please ask for commercial support.
Thx.
