### ISSUE TITLE
Problems in docker

### ISSUE THREAD

**Issue by vagabondan** [zabbix/zabbix-community-docker#51]
Run:
docker run -d --name zabbix -p 8080:80 -p 10061:10051 -v /etc/localtime:/etc/localtime:ro --env="ZS_DBHost=*****_" --env="ZS_DBUser=zabbix" --env="ZS_DBPassword=**_***"  monitoringartist/zabbix-3.0-xxl:latest
Get:
1. nginx and php-fpm don't  start automatically. I wonder they should be added to bootstrap.sh.
2. If you want to get statistics from google-analytics then consider to launch curl as daemon (with & at the end of commands), because there could be no Internet connection (curl just hangs in this/my case)

**Comment by jangaraj** [comment]
Please provide docker logs - see troubleshooting https://github.com/monitoringartist/zabbix-xxl#docker-troubleshooting. Thx.

1.) Nope, they are managed by supervisord
2.) I agree, enterprise networks don't have internet access usually and it can be a problem - I'll improve it. BTW you can use env variable to disable analytics - see readme

**Comment by vagabondan** [comment]
1.) The first one was the consequence of the second problem as I understood:
supervisor tries to launch command in analytics.conf (it executes first):

`[eventlistener:analytics]
command = /usr/bin/bash -c 'while true; do sleep 3600; /usr/bin/bash /config/init/12-xxl-ping.sh; done'`

...where 12-xxl-ping.sh contains curl to google-analytics => and supervisor hangs.

2.) --env="XXL_analytics=false" results in error:

Below is debug of /config/init/11-xxl.sh:

> [LOG 13:42:03] Preparing XXL features
> xxl_config
> ++ xxl_config
> +++ md5sum
> +++ awk -F - '{print $1}'
> +++ tr -d ' '
> ++++ hostname
> ++ cid=4583fab564f685d9fa27ab31cf8599ca
> ++ XXL_analytics=false
> ++ true
> ++ false
> ++ false
> ++ sed -i '/'\''zapix.php'\''/d' /usr/local/src/zabbix/frontends/php/include/menu.inc.php
> ++ rm -rf /usr/local/src/zabbix/frontends/php/zapix/ /usr/local/src/zabbix/frontends/php/zapix.php
> ++ false
> ++ sed -i '/'\''grapher.php'\''/d' /usr/local/src/zabbix/frontends/php/include/menu.inc.php
> ++ rm -rf /usr/local/src/zabbix/frontends/php/grapher/ /usr/local/src/zabbix/frontends/php/grapher.php
> ++ false
> `++ sed -i '/<script>(function(i,s,o,g,r,a,m){i['\''GoogleAnalyticsObject'\'']=r;i[r]=i[r]||function(){(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)})(window,document,'\''script'\'','\''//www.google-analytics.com/analytics.js'\'','\''ga'\'');ga('\''create'\'','\''UA-72810204-2'\'','\''auto'\'');ga('\''send'\'','\''pageview'\'');</script>/d' /usr/local/src/zabbix/frontends/php/include/menu.inc.php
> `
> sed: -e expression #1, char 273: unknown command: `/'

3.) After resolving issue with sed syntax (need backslashes before each slash in addresses and tags) curl problem comes back, because of curls in /config/init/11-xxl.sh

**Comment by vagabondan** [comment]
Closed by mistake

**Comment by vagabondan** [comment]
/config/init/11-xxl.sh:
Section below has to be reviewed I think:

```
  if ! $XXL_analytics; then
    sed -i "/<script>(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)})(window,document,'script','\/\/www.google-analytics.com\/analytics.js','ga');ga('create','UA-72810204-2','auto');ga('send','pageview');<\/script>/d" /usr/local/src/zabbix/frontends/php/include/menu.inc.php
    export ZABBIX_VERSIONP=$(echo $ZABBIX_VERSION | tr -d '/')
    curl -ks -o /dev/null "http://www.google-analytics.com/r/collect?v=1&tid=UA-72810204-2&cid=${cid}&t=event&ec=Ping&ea=Version&el=${ZABBIX_VERSIONP}&ev=1&dp=%2F&dl=http%3A%2F%2Fgithub.com%2Fmonitoringartist%2Fzabbix-xxl" &> /dev/null
    curl -ks -o /dev/null "http://www.google-analytics.com/r/collect?v=1&tid=UA-72810204-2&cid=${cid}&t=event&ec=Stat&ea=Version&el=${ZABBIX_VERSIONP}&ev=1&dp=%2F&dl=http%3A%2F%2Fgithub.com%2Fmonitoringartist%2Fzabbix-xxl" &> /dev/null
    if $ZS_enabled; then
      curl -ks -o /dev/null "http://www.google-analytics.com/r/collect?v=1&tid=UA-72810204-2&cid=${cid}&t=event&ec=Stat&ea=ZS_enabled&el=${ZS_enabled}&ev=1&dp=%2F&dl=http%3A%2F%2Fgithub.com%2Fmonitoringartist%2Fzabbix-xxl" &> /dev/null
    fi
    if $ZA_enabled; then
      curl -ks -o /dev/null "http://www.google-analytics.com/r/collect?v=1&tid=UA-72810204-2&cid=${cid}&t=event&ec=Stat&ea=ZA_enabled&el=${ZA_enabled}&ev=1&dp=%2F&dl=http%3A%2F%2Fgithub.com%2Fmonitoringartist%2Fzabbix-xxl" &> /dev/null
    fi
    if $ZW_enabled; then
      curl -ks -o /dev/null "http://www.google-analytics.com/r/collect?v=1&tid=UA-72810204-2&cid=${cid}&t=event&ec=Stat&ea=ZW_enabled&el=${ZW_enabled}&ev=1&dp=%2F&dl=http%3A%2F%2Fgithub.com%2Fmonitoringartist%2Fzabbix-xxl" &> /dev/null
    fi
    if $ZP_enabled; then
      curl -ks -o /dev/null "http://www.google-analytics.com/r/collect?v=1&tid=UA-72810204-2&cid=${cid}&t=event&ec=Stat&ea=ZP_enabled&el=${ZP_enabled}&ev=1&dp=%2F&dl=http%3A%2F%2Fgithub.com%2Fmonitoringartist%2Fzabbix-xxl" &> /dev/null
    fi
  fi

```

**Comment by jangaraj** [comment]
Done, please test `monitoringartist/zabbix-3.0-xxl:dev` image.

**Comment by jangaraj** [comment]
Done.
