### ISSUE TITLE
ICMP Ping checks fail

### ISSUE THREAD

**Issue by JanKoppe** [zabbix/zabbix-community-docker#53]
`fping failed: sh: /usr/sbin/fping6: Device not a stream` 

I get this error message when I try to use a ICMP Ping check for a IPv4 Host. Running the fping command with `docker exec` works.

**Comment by jangaraj** [comment]
I need details to replicate your problem:
- how did you start containers
- versions: zabbix/docker
- docker info
- docker/zabbix logs
- how did you configure imcp check and how did you verify it with `docker exec`
- ...

**Comment by jangaraj** [comment]
No response from the user.
