### ISSUE TITLE
Broken SSL CAs

### ISSUE THREAD

**Issue by KostyaEsmukov** [zabbix/zabbix-community-docker#58]
The ...

```
### Option: SSLCALocation
#       Override the location of certificate authority (CA) files for SSL server certificate verification.
#       If not set, system-wide directory will be used.
#       This parameter is used only in web monitoring.
#
# Mandatory: no
# Default:
# SSLCALocation=
SSLCALocation=
```

... part of config breaks CA for zabbix: enabling the `SSL verify *` options for smtp cause `Problem with the SSL CA cert (path? access rights?): server response timeout` errors. Using custom `zabbix_server.conf` without this line fixes the issue.

**Comment by jangaraj** [comment]
Hi Kostya, 

Thank you for your report. Could you test it with `:dev` Docker image please. There is already different handling of environment variables and it should be fine.

**Comment by KostyaEsmukov** [comment]
Hi Jan,

The `:dev` seems to be fine, thanks.

**Comment by jangaraj** [comment]
Thank you for confirmation. I'll keep this issue opened until I'll update production images.

**Comment by jangaraj** [comment]
Done. Fixed images are available.
