### ISSUE TITLE
Container fails to restart when `ZJ_enabled=true`

### ISSUE THREAD

**Issue by fernandezcuesta** [zabbix/zabbix-community-docker#59]
When zabbix java gateway is started, [`bootstrap.sh`](https://github.com/monitoringartist/zabbix-xxl/blob/master/Dockerfile/zabbix-3.0/container-files-zabbix/config/init/bootstrap.sh#L198) fails to move a file which doesn't exist anymore, then exits abruptly.

**Comment by jangaraj** [comment]
Fix: PR #60

**Comment by jangaraj** [comment]
Done. Fixed images are available.
