### ISSUE TITLE
docker: Error response from daemon: Cannot link to a non running container: /zabbix-db AS /zabbix/zabbix.db.

### ISSUE THREAD

**Issue by kovalroma** [zabbix/zabbix-community-docker#61]
Hello!
I am trying to install zabbix docker. 

When I run this 
docker run \
    -d \
    --name zabbix \
    -p 80:80 \
    -p 10051:10051 \
    -v /etc/localtime:/etc/localtime:ro \
    --link zabbix-db:zabbix.db \
    --env="ZS_DBHost=zabbix.db" \
    --env="ZS_DBUser=zabbix" \
    --env="ZS_DBPassword=my_password" \
    monitoringartist/zabbix-3.0-xxl:latest

I've got error
ocker: Error response from daemon: Cannot link to a non running container: /zabbix-db AS /zabbix/zabbix.db.

Here my containers
sudo docker ps -a
sudo: unable to resolve host ip-172-30-0-172
CONTAINER ID        IMAGE                                    COMMAND                  CREATED             STATUS                     PORTS               NAMES
7021ac6c4774        monitoringartist/zabbix-3.0-xxl:latest   "/config/bootstrap.sh"   3 minutes ago       Created                                        zabbix
df5071136d72        monitoringartist/zabbix-db-mariadb       "/run.sh"                3 minutes ago       Exited (1) 3 minutes ago                       zabbix-db
229ca6830d94        busybox:latest                           "sh"                     3 minutes ago       Exited (0) 3 minutes ago                       zabbix-db-storage

I am doing exactly what manual says.
Where is my problem? 

I am trying to do on my test Amazon instance.

**Comment by jangaraj** [comment]
Check docker logs of zabbix-db container (`docker logs zabbix-db`). https://github.com/monitoringartist/zabbix-xxl#docker-troubleshooting. Your zabbix-db container has some issue (`Exited (1) 3 minutes ago`).
