### ISSUE TITLE
Segmentation fault when using storage driver 'overlay' for dockerd

### ISSUE THREAD

**Issue by fmax** [zabbix/zabbix-community-docker#63]
docker daemon running options:
/usr/bin/dockerd -H fd:// --storage-driver=overlay --dns 172.17.0.1 -H tcp://0.0.0.0:2375 -H unix:///var/run/docker.sock

this error could get reproduced
# starting container

docker run -d --name zabbix2 -p 80:8181 -p 10051:10051 -v /etc/localtime:/etc/localtime:ro monitoringartist/zabbix-3.0-xxl:latest
# container logs

docker logs zabbix2
Nginx status page: allowed address set to 127.0.0.1.
PHP-FPM status page: allowed address set to 127.0.0.1.
[LOG 16:54:50] Preparing XXL features
[LOG 16:54:50] XXL configuration done.
[LOG 16:54:50] Preparing server configuration
[LOG 16:54:50] Waiting for API, it's still not available
[LOG 16:54:50] Config updated.
[LOG 16:54:50] Enabling logging and pid management
/config/init/bootstrap.sh: line 53:   307 Segmentation fault      chown root:$ZS_User /usr/sbin/fping
# informations of docker and OS

docker info
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 1
Server Version: 1.12.1
Storage Driver: overlay
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host bridge overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-36-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 770.4 MiB
Name: ubuntu16-docker
ID: QSST:URMA:LYAB:QE26:4DVO:K4MC:ZDFA:NC2M:BDNV:MSMD:KFEN:7NQ2
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8

**Comment by jangaraj** [comment]
It's overlayfs problem. devicemapper, aufs don't have this issue. I've tested on my system and I got https://github.com/docker/docker/issues/18295 Workoaround `--privileged` has fixed it. I don't recommend overlay or you will need to debug overlays issues. 
I'm closing it for now. It's not a image issue.

**Comment by fmax** [comment]
about storage driver:
- 'aufs' is working
- 'overlay' resulting in a segmentation fault

thanks for your hints, but doesn't solve the problem:
- '--privileged' => segmentation fault
- disabled apparmor 'service apparmor teardown' => segmentation fault
- kernel is already the latest '4.4.0-36-generic'

so i will try to modify the 'bootstrap.sh' script and build docker image locally.

output of 'dmesg'
[Mon Sep 19 10:28:05 2016] ------------[ cut here ]------------
[Mon Sep 19 10:28:05 2016] kernel BUG at /build/linux-a2WvEb/linux-4.4.0/fs/attr.c:280!
[Mon Sep 19 10:28:05 2016] invalid opcode: 0000 [#1] SMP
[Mon Sep 19 10:28:05 2016] Modules linked in: xt_nat xt_tcpudp veth ipt_MASQUERADE nf_nat_masquerade_ipv4 xfrm_user xfrm_algo iptable_nat nf_conntrack_ipv4 nf_defrag_ipv4 nf_nat_ipv4 xt_addrtype iptable_filter ip_tables xt_conntrack x_tables nf_nat nf_conntrack br_netfilter bridge stp llc overlay ppdev crct10dif_pclmul crc32_pclmul aesni_intel aes_x86_64 lrw snd_intel8x0 vboxvideo gf128mul snd_ac97_codec glue_helper ablk_helper cryptd ttm input_leds drm_kms_helper serio_raw joydev ac97_bus snd_pcm i2c_piix4 snd_timer drm 8250_fintek fb_sys_fops snd syscopyarea sysfillrect parport_pc sysimgblt parport soundcore mac_hid vboxguest autofs4 hid_generic usbhid hid psmouse ahci libahci fjes video e1000 pata_acpi
[Mon Sep 19 10:28:05 2016] CPU: 0 PID: 1412 Comm: chown Not tainted 4.4.0-36-generic #55-Ubuntu
[Mon Sep 19 10:28:05 2016] Hardware name: innotek GmbH VirtualBox/VirtualBox, BIOS VirtualBox 12/01/2006
[Mon Sep 19 10:28:05 2016] task: ffff880029ae0000 ti: ffff88002c800000 task.ti: ffff88002c800000
[Mon Sep 19 10:28:05 2016] RIP: 0010:[<ffffffff8122a3f3>]  [<ffffffff8122a3f3>] notify_change+0x303/0x360
....

**Comment by jangaraj** [comment]
Try `--security-opt seccomp=unconfined`, because `Security Options: apparmor seccomp`. Are you using any quotas or ACL for filesystem (in Virtualbox or in real host)? Try it with VMWare player. Is it docker-machine VM?

**Comment by fmax** [comment]
after i saw segementation fault first time running on a hardware docker node with intel atom CPU (ubuntu 16 LTS kernel 4.4.0-36-generic), i decided to make some tests in a oracle virtual box.

so all this tests now running in a virtual box with ubuntu 16 LTS & kernel 'Linux version 4.4.0-36-generic (buildd@lcy01-01) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.2) ) #55-Ubuntu SMP Thu Aug 11 18:01:55 UTC 2016'

there are no quotas or ACL set.

next test also ends with segfault:
service apparmor teardown
- Unloading AppArmor profiles      [ OK ]

docker run -d --privileged --security-opt seccomp=unconfined --name zabbix-server -p 80:8181 -p 10051:10051 -v /etc/localtime:/etc/localtime:ro monitoringartist/zabbix-3.0-xxl

docker logs zabbix-server
Nginx status page: allowed address set to 127.0.0.1.
PHP-FPM status page: allowed address set to 127.0.0.1.
[LOG 16:42:03] Preparing XXL features
[LOG 16:42:03] XXL configuration done.
[LOG 16:42:03] Waiting for API, it's still not available
[LOG 16:42:03] Preparing server configuration
[LOG 16:42:03] Config updated.
[LOG 16:42:03] Enabling logging and pid management
/config/init/bootstrap.sh: line 53:   307 Segmentation fault      chown root:$ZS_User /usr/sbin/fping

---

i've modified bootstrap.sh - commented 'chown' and set executable flag for everyone on fping(6)

vi zabbix-xxl/Dockerfile/zabbix-xxl/container-files-zabbix/config/init/bootstrap.sh
...
  chmod u+s /usr/bin/ping
  #chown root:$ZS_User /usr/sbin/fping
  #chown root:$ZS_User /usr/sbin/fping6
  chmod 4711 /usr/sbin/fping
  chmod 4711 /usr/sbin/fping6
...

after building docker image and starting is working without any troubles.
when getting into running container using bash, i can see the changed permissions:
docker exec -ti my-zabbix-server /bin/bash
[root@8f89218bdf15 /]# ls -la /usr/sbin/fping*
-rws--x--x 1 root root 89839 Sep 19 12:32 /usr/sbin/fping
-rws--x--x 1 root root 90492 Sep 19 12:32 /usr/sbin/fping6

i think, this would work for me

**Comment by jangaraj** [comment]
Thank you for your investigation. I'll test/add it later.

**Comment by jangaraj** [comment]
Done. All 3.x image https://hub.docker.com/r/monitoringartist/zabbix-xxl/tags/ use:

```
chmod 4711 /usr/sbin/fping
chmod 4711 /usr/sbin/fping6
```

Please test it.
Thanks!
