### ISSUE TITLE
Failing to Start

### ISSUE THREAD

**Issue by montge** [zabbix/zabbix-community-docker#65]
docker run     -it     --name zabbix     -p 480:80     -p 10051:10051     -v /etc/localtime:/etc/localtime:ro     --link zabbix-db:zabbix.db     --env="ZS_DBHost=zabbix.db"     --env="ZS_DBUser=zabbix"     --env="ZS_DBPassword="     monitoringartist/zabbix-3.0-xxl:latest /bin/bash

[root@7bd261ab8470 /]# /config/bootstrap.sh 
Nginx status page: allowed address set to 127.0.0.1.
PHP-FPM status page: allowed address set to 127.0.0.1.
[LOG 14:03:23] Preparing XXL features
rm: cannot remove ‘/usr/local/src/zabbix/frontends/php/zapix/assets’: Directory not empty
rm: cannot remove ‘/usr/local/src/zabbix/frontends/php/zapix/css/bootstrap’: Directory not empty
rm: cannot remove ‘/usr/local/src/zabbix/frontends/php/zapix/css/img’: Directory not empty
rm: cannot remove ‘/usr/local/src/zabbix/frontends/php/zapix/js’: Directory not empty

[root@7bd261ab8470 assets]# ls -l
ls: cannot access favicon.ico: No such file or directory
ls: cannot access favicon.png: No such file or directory
total 0
?????????? ? ? ? ?            ? favicon.ico
?????????? ? ? ? ?            ? favicon.png

**Comment by jangaraj** [comment]
Which storage driver is used by your docker daemon?

**Comment by montge** [comment]
docker run     -d --restart="always"     --name zabbix     -p 480:80     -p 10051:10051     -v /etc/localtime:/etc/localtime:ro     --link zabbix-db:zabbix.db     --env="ZS_DBHost=zabbix.db"     --env="ZS_DBUser=zabbix"     --env="ZS_DBPassword="     --env="XXL_searcher=true" --env="XXL_analytics=false" --env="XXL_zapix=true" --env="XXL_grapher=true" monitoringartist/zabbix-3.0-xxl:latest

Running this command allowed it to start.  Not the additional ENV's.

**Comment by montge** [comment]
Storage Driver: overlay
 Backing Filesystem: xfs

**Comment by jangaraj** [comment]
Overlayfs - yeah, I was expecting it. That's a issue/question for overlayfs developers, why regular FS operation (rm -rf unused code in this case) is failing. You can try add additional permissions `--privileged --security-opt seccomp=unconfined`, but I'm skeptic. Workaround: switch to aufs/devicemapper storage driver.

**Comment by sergsadovyi** [comment]
Overlay driver problem fix:
https://github.com/monitoringartist/dockbix-agent-xxl/issues/16#issuecomment-288356609
