### ISSUE TITLE
Is Zabbix agent XXL required?

### ISSUE THREAD

**Issue by Rickkwa** [zabbix/zabbix-community-docker#67]
If I use Zabbix XXL for the zabbix-server, is it mandatory that the agents use Zabbix agent XXL? Does this work for native zabbix agents?

**Comment by jangaraj** [comment]
Yes, you can use native Zabbix agent. Zabbix agent XXL is limited native Zabbix agent, but with Docker monitoring support.

**Comment by Rickkwa** [comment]
Does it work the other way around? Ie. Native Zabbix-server using Zabbix-agent-XXL while keeping the ability to monitor Docker services.

**Comment by jangaraj** [comment]
Yes, there no restriction to use what you want.

**Comment by polcape** [comment]
So, how I monitoring the container (like with dockebix-agent-xxl) in a docker host with zabbix-xxl (server) running?

**Comment by jangaraj** [comment]
@polcape That's a generic question, not a issue. Please read provided READMEs.

**Comment by polcape** [comment]
@jangaraj I have read the README but I not found answer to my question, so I have posted here... Please can you provide me some links where is the answer?
