### ISSUE TITLE
Database not upgraded

### ISSUE THREAD

**Issue by Guibod** [zabbix/zabbix-community-docker#68]
Upgraded my image today to latest (3.0.4) and got this issue:

```
2016-10-24 13:48:31,621 DEBG 'zabbix-server' stdout output:
  1781:20161024:134831.620 The server does not match Zabbix database. Current database version (mandatory/optional): 03020000/03020000. Required mandatory version: 03000000.
```

That's unfortunate because I'm pretty sure that I already saw Zabbix XXL automagically upgrade the database once.
I can't be sure of that last version I used, but that was a 3.0.x image.
How can i get out of this issue without wiping my db ?

**Comment by jangaraj** [comment]
Auto DB upgrade is standard zabbix feature - it's not an additional feature. Restore your backup DB and you will be fine. Or start newer image, which will match DB version. 3.0.5/3.2.1 version are available as well https://hub.docker.com/r/monitoringartist/zabbix-xxl/tags/ 

Golden rule: backup/backup/backup.

**Comment by Guibod** [comment]
Ok then thanks.

**Comment by Guibod** [comment]
Problem was that I used the old repository `zabbix-3.0-xxl` in my automated install while using `zabbix-xxl` in stress situation when my Zabbix crashed last time. So I was running 3.0.4 on a 3.2.1 database.
