### ISSUE TITLE
need to increase CacheSize

### ISSUE THREAD

**Issue by waffel** [zabbix/zabbix-community-docker#70]
After starting zabbix-server i see error related to mem cache.

I needed to increate the cache site to 10M

I have done this with following docker-compose entry (version '1')

environment:
- ZS_CacheSize=10M

without this, zabbix server does not start (I have imported database from version 2.4)

**Comment by jangaraj** [comment]
This is not a issue. It's a standard Zabbix behaviour and it's said what you need to do. You did correct configuring.

**Comment by waffel** [comment]
ok, thanks ... would be nice to gat an hint in the documentation :-)

**Comment by jangaraj** [comment]
Feel free to create PR. Current doc:

```
Use environment variables to config Zabbix and Zabbix web UI (PHP). Default container variables or default Zabbix are used:
```
