### ISSUE TITLE
ZJ_Enabled doesn't enable pollers

### ISSUE THREAD

**Issue by montge** [zabbix/zabbix-community-docker#71]
It doesn't appear that the ZJ_Enabled adds to the /usr/local/etc/zabbix_server.conf the proper parameters for enabling the poller.  Expected result would have the following parameters populated.

JavaGateway=$ZJ_LISTEN_IP
JavaGatewayPort=$ZJ_LISTEN_PORT
StartJavaPollers=$ZJ_START_POLLERS

This was with the 3.0 based version.

**Comment by jangaraj** [comment]
That's correct. There is no `ZJ_START_POLLERS` env variable https://github.com/monitoringartist/zabbix-xxl/tree/master/Dockerfile/zabbix-xxl#environmental-variables

`StartJavaPollers, JavaGatewayPort, JavaGateway` are Zabbix server settings https://www.zabbix.com/documentation/3.0/manual/appendix/config/zabbix_server, so you need env variables `ZS_StartJavaPollers, ZS_JavaGatewayPort, ZS_JavaGateway` to configure your Zabbix server.

**Comment by montge** [comment]
Please add to documentation on docker hub.  Found similar workaround.  Would recommend that environment variables be set since this is a duplicate variable.

--env="ZJ_enabled=true"     --env="ZJ_LISTEN_IP=127.0.0.1" --env="ZS_JavaGateway=127.0.0.1" --env="ZS_JavaGatewayPort=10052" --env="ZS_StartJavaPollers=5"

**Comment by jangaraj** [comment]
Nope. Java gateway and Java poller(s) are independent components, so user should to have options to configure them independently.
