### ISSUE TITLE
Issues with UI

### ISSUE THREAD

**Issue by yaniveliash** [zabbix/zabbix-community-docker#73]
I've several buttons that are misplaced in the UI
under `maintenance > hosts`

A more visual explanation:
https://s17.postimg.org/sc7nf7x73/Screenshot_at_Dec_06_13_08_49.png

**Comment by jangaraj** [comment]
Which docker image version did you use and what did you do? How did you start container? Try clean your browser cache. Your screenshot is broken.

**Comment by yaniveliash** [comment]
I cleared my cache and that did that trick, thanks :)
