### ISSUE TITLE
No locales in latest image

### ISSUE THREAD

**Issue by YouSysAdmin** [zabbix/zabbix-community-docker#75]
in docker-compose.yml
```zabbix-server:
     restart: always
     image: monitoringartist/zabbix-xxl:latest
     depends_on:
     - zabbix-db

```
result in Zabbix config interface: 
```You are not able to choose some of the languages, because locales for them are not installed on the web server.```
avaliable only en_GB locale.

**Comment by jangaraj** [comment]
Thanks. CentOS has (had) a problem with glibc-common. Now it builds locales in the docker build process manually.
