### ISSUE TITLE
Dark theme - layout problems

### ISSUE THREAD

**Issue by erikbotta** [zabbix/zabbix-community-docker#76]
I have problem with dark-theme. See screenshots. Latest Chrome. Blue theme is OK.
![zabbix_problem](https://cloud.githubusercontent.com/assets/832402/21505852/6a887c66-cc6b-11e6-9db7-97ce35f1c69f.png)
![zabbix_problem_2](https://cloud.githubusercontent.com/assets/832402/21505867/907e9428-cc6b-11e6-99b7-f875a6b56a23.png)

**Comment by jangaraj** [comment]
Try to clean your browser cache.

**Comment by erikbotta** [comment]
Damned, sry for the rookie report. It is OK now with Shift+F5 :)
