### ISSUE TITLE
UserParameter

### ISSUE THREAD

**Issue by centurion800** [zabbix/zabbix-community-docker#79]
Hi. great work. I added UserParameter to /usr/local/etc/zabbix_agentd.conf, but after reboot container my changes not saves. How i can add UserParameter?

**Comment by jangaraj** [comment]
That's not a issue, but request for support - closing. Thanks!

Clue: one option can be volume `-v  /myhostpath/zabbix_agentd.conf:/usr/local/etc/zabbix_agentd.conf` - please read Docker doc about volumes for more details.

**Comment by centurion800** [comment]
Container stopped
Stopped since a minute with exit code 4
2017-02-07T22:52:00.978527553Z sed: cannot rename /usr/local/etc/seddoqaXk: Device or resource busy
