### ISSUE TITLE
Entire server constantly restarts after setting up e-mail

### ISSUE THREAD

**Issue by SamyCoenen** [zabbix/zabbix-community-docker#81]
When setting the SMTP e-mail in the following format: zabbix@company.com and enabling authentication, the entire server goes down after it tries to send an e-mail.

the logs are in a constant loop: 
```
zabbix-db_1      | 170208 13:05:54 [Warning] Aborted connection 388 to db: 'zabbix' user: 'zabbix' host: '172.18.0.3' (Got an error reading communication packets)
zabbix-server_1  |   1074:20170208:130556.719 Zabbix Server stopped. Zabbix 3.2.3 (2016-12-26) (revision 64610).
zabbix-server_1  | 
zabbix-server_1  | 2017-02-08 13:05:58,728 DEBG fd 19 closed, stopped monitoring <POutputDispatcher at 15781544 for <Subprocess at 15233248 with name zabbix-server in state RUNNING> (stdout)>
zabbix-server_1  | 2017-02-08 13:05:58,729 DEBG fd 25 closed, stopped monitoring <POutputDispatcher at 15781616 for <Subprocess at 15233248 with name zabbix-server in state RUNNING> (stderr)>
zabbix-server_1  | 2017-02-08 13:05:58,730 INFO exited: zabbix-server (exit status 232; not expected)
zabbix-server_1  | 2017-02-08 13:05:58,731 DEBG received SIGCLD indicating a child quit
zabbix-server_1  | 2017-02-08 13:05:59,735 INFO spawned: 'zabbix-server' with pid 1105
zabbix-server_1  | 2017-02-08 13:05:59,773 DEBG 'zabbix-server' stdout output:
zabbix-server_1  | Starting Zabbix Server. Zabbix 3.2.3 (2016-12-26) (revision 64610).
```

Fixed by 
- disabling authentication
- using format: Zabbix HQ <zabbix@company.com>

**Comment by jangaraj** [comment]
Could you provides more details about (I'm not sure what are you doing):
_When setting the SMTP e-mail in the following format: zabbix@company.com and enabling authentication, the entire server goes down after it tries to send an e-mail._

**Comment by SamyCoenen** [comment]
Sure, I will list my steps:

  Administration -> Media types -> Email
  Edit field: SMTP email -> zabbix@company.com
  Edit field: Authentication -> password

After I do this, my trigger action tries to send an email to my Exchange 2013 e-mail server and my whole zabbix server inside the container starts constantly restarting.

**Comment by jangaraj** [comment]
Could you please increase log level and then I would like to see zabbix server logs. Also check your db logs. It looks like a problem with db connectivity.

**Comment by jangaraj** [comment]
Could you please increase log level and then I would like to see zabbix server logs. Also check your db logs. It looks like a problem with db connectivity.

**Comment by SamyCoenen** [comment]
System has been stable since fixing it by using other options. It did seem like it corrupted or created some kind of incompatibility between both containers.
