### ISSUE TITLE
running via docker command does not have the same effect with runnig docker compose

### ISSUE THREAD

**Issue by oguzy** [zabbix/zabbix-community-docker#82]
I am running the images after  build them as below

#

```
 create /var/lib/mysql as persistent volume storage
docker run -d -v /var/lib/mysql --name zabbix-db-storage busybox:latest

# start DB for Zabbix - default 1GB innodb_buffer_pool_size is used
docker run \
    -d \
    --name zabbix-db \
    -v /backups:/backups \
    -v /etc/localtime:/etc/localtime:ro \
    --volumes-from zabbix-db-storage \
    --env="MARIADB_USER=zabbix" \
    --env="MARIADB_PASS=my_password" \
   zabbix-db-mariadb

# start Zabbix linked to started DB
docker run \
    -d \
    --name zabbix \
    -p 80:80 \
    -p 10051:10051 \
    -v /etc/localtime:/etc/localtime:ro \
    --link zabbix-db:zabbix.db \
    --env="ZS_DBHost=zabbix.db" \
    --env="ZS_DBUser=zabbix" \
    --env="ZS_DBPassword=my_password" \
   zabbix-xxl:latest
# wait ~60 seconds for Zabbix initialization
# Zabbix web will be available on the port 80, Zabbix server on the port 10051
```

zabbix-xxl and  zabbix-db-mariadb are the local images i create dby entering the related directory and run docker build. When i enter the web ui, i dont see dashboards. Any idea what missing?

**Comment by jangaraj** [comment]
> When i enter the web ui, i dont see dashboards.

Which dashboards? You are starting DB from the scratch.

**Comment by oguzy** [comment]
When i enter the zabbix ui, favorite graphs, favorite screens and favorite maps, all are empty. But when i run docker-compose up,  i can see they are filled.

**Comment by jangaraj** [comment]
docker-compose uses different container name schema. So it's connecting to different `zabbix-db-storage` container where data are stored. It's not a problem with image, but only configuration problem - out of the scope this project. Please check docker/docker-compose documentation.

**Comment by oguzy** [comment]
when i check docker-compose.yml, i don't see a different part from the one that i am doing above. Creating volume from busybox, just the images are monitoringartist/zabbix-db-mariadb and monitoringartist/zabbix-xxl:latest, instead i am using zabbix-db-mariadb which is created via docker built -t zabbix-db-mariadb . from the github source.

**Comment by jangaraj** [comment]
Run docker-compose and check docker ps. Docker-compose uses some prefix for container name, etc. As I said - check documentation or I can provide commercial paid support for this your problem.
