### ISSUE TITLE
How to update image properly without data losing

### ISSUE THREAD

**Issue by sonanchenko** [zabbix/zabbix-community-docker#89]
Hello Everyone.

I'm running 3.2.5 version now and would like to get up-to-date version (as far as I see, 3.2.6 is available).
I haven't found update checker and looking for docker image upgrade.

Could you please post the safe procedure that I can follow (and then create script for automation)
to get latest version without losing existing configuration?

Could you please assist me with this issue?

I will be grateful for any help you can provide.

**Comment by jangaraj** [comment]
Generally: use proper image tags. For example: `monitoringartist/zabbix-xxl:3.2.6`, instead of `latest` tag. List of available tags https://hub.docker.com/r/monitoringartist/zabbix-xxl/tags/

**Comment by sonanchenko** [comment]
Yes. You are right.
But this requires manual updates and checking which tags are available.
"Latest" tab enables doing so automatically by cron.
Please correct me if I am wrong.

I used to have similar approach for other docker:

sudo docker stop $CONTAINER
sudo docker rm -f $CONTAINER
sudo docker pull $CONTAINER_REPO/$CONTAINER_REPO_NAME:latest
sudo docker run $CONTAINER_RUN_PARAMETERS
(data storage as well as configs are kept unchanged)

So what are the best practices about updating this one?

**Comment by jangaraj** [comment]
My recommendation:

3.2.5:
```
docker run \
    -d \
    --name zabbix \
    -p 80:80 \
    -p 10051:10051 \
    -v /etc/localtime:/etc/localtime:ro \
    --link zabbix-db:zabbix.db \
    --env="ZS_DBHost=zabbix.db" \
    --env="ZS_DBUser=zabbix" \
    --env="ZS_DBPassword=my_password" \
    --env="XXL_zapix=true" \
    --env="XXL_grapher=true" \
    monitoringartist/zabbix-xxl:3.2.5
```
3.2.6:
```
docker run \
    -d \
    --name zabbix \
    -p 80:80 \
    -p 10051:10051 \
    -v /etc/localtime:/etc/localtime:ro \
    --link zabbix-db:zabbix.db \
    --env="ZS_DBHost=zabbix.db" \
    --env="ZS_DBUser=zabbix" \
    --env="ZS_DBPassword=my_password" \
    --env="XXL_zapix=true" \
    --env="XXL_grapher=true" \
    monitoringartist/zabbix-xxl:3.2.6
```

But it's up to you how did you set it up. You know what's your infrastructure and which risk level are you able to accept. Best practice: automate everything and backups. I use puppet in my real implementation and all my containers are running as systemd services - but this project is not here to teach users how to do it. It's just "packaging" of Zabbix + some additional features into Docker image. If you need support, then please hire me/learn more - there is a tones of knowledge on the internet.

BTW: there will "update checker" feature released in this image, preview:
![dockbix-xxl-updatechecker](https://cloud.githubusercontent.com/assets/1182932/26752456/1075ae98-4848-11e7-842d-b456babb5a98.png)
