### ISSUE TITLE
Include schema files?

### ISSUE THREAD

**Issue by vanosg** [zabbix/zabbix-community-docker#9]
Perhaps I'm doing it the wrong way, but since this docker version of zabbix requires a separate mysql container (which I agree with!), perhaps it would be nice to include the needed schema files somewhere in the base structure. While not world-ending, I had to download the tarfile to grab the schema files with which to create my mysql container- it was just another several minutes and steps that could perhaps be avoided. Or, maybe even generate an official zabbix-mysql container that already has the user and schemas loaded? Just a thought. Thanks

... or am I doing it wrong? :)

**Comment by jangaraj** [comment]
You don't need a Zabbix DB schema. That's included in bootstrap process. Bootstrapping is trying to detect Zabbix DB. If Zabbix DB doesn't exist, then Zabbix DB and schema is created + basic Zabbix data files are imported => this is already implemented. Please just follow https://github.com/zabbix/zabbix-community-docker/tree/master/Dockerfile/zabbix-server-2.4 and then check your containers logs.

**Comment by vanosg** [comment]
That's great that it does that already. Might I suggest clarifying that process in the README? The opening line says it has 'everything', but then the very next line says it requires an external MySQL container. Talking a little more about what is or isn't needed in the README would be very helpful for the average user. Thanks again!

**Comment by jangaraj** [comment]
It is in the README alredy: _See [README of zabbix-server-2.4](https://github.com/zabbix/zabbix-community-docker/tree/master/Dockerfile/zabbix-server-2.4) for more details._

**Comment by vanosg** [comment]
That's what I'm trying to say:

```
Compiled zabbix-server with almost all features (MySQL, Java, SNMP, Curl, Ipmi) and Zabbix web 
UI based on CentOS 7, Supervisor, Nginx, PHP. Image requires external MySQL database (you can 
run MySQL also as Docker container).
```

It contradicts itself- it says it compiles with MySQL (which I am assuming means it has the mysql server as part of the container locally? Maybe it doesn't, hence the confusion) Then says it requires an external MySQL container. I would suggest that you clarify one of those two sentences, and maybe add a sentence that says "on first run, the zabbix container will connect to the MySQL container and create the appropriate database schema" or something like that.

**Comment by jangaraj** [comment]
MySQL => MySQL support. Feel free to open PR if you know how to write it better.
