### ISSUE TITLE
Docker images are not started after server reboot

### ISSUE THREAD

**Issue by sonanchenko** [zabbix/zabbix-community-docker#90]
Hi2All,

3.2.5 version in container.
Each time I reboot my server, I have to start containers manually:

>docker start zabbix-db-storage && sleep 5 && docker start zabbix-db && sleep 5 && docker start zabbix
Am I doing something wrong?

I've tried to find info why they were unable to start, but didn't managed to do so.
Could you please assist me in troubleshooting?

The final goal here is having zabbix container running all the time (watchdog?) in any cases.
As far as I see from docker logs zabbix:

```
2017-06-03 08:25:29,986 DEBG 'zabbix-server' stdout output:
   374:20170603:082529.985 [Z3005] query failed: [2003] Can't connect to MySQL server on 'zabbix.db' (111) [begin;]
   374:20170603:082529.986 [Z3001] connection to database 'zabbix' failed: [2003] Can't connect to MySQL server on 'zabbix.db' (111)
   374:20170603:082529.986 database is down: reconnecting in 10 seconds
```

Probably, there should be some order of containers startup.
I'm wondering if someone has faced the same.

I will be grateful for any help you can provide.

**Comment by jangaraj** [comment]
That's generic Docker question, please learn more about container concept - official doc and restart policy is good start point - https://docs.docker.com/engine/reference/run/#restart-policies-restart
