### ISSUE TITLE
rm: cannot remove 

### ISSUE THREAD

**Issue by yangswei** [zabbix/zabbix-community-docker#91]
[LOG 02:06:01] Preparing XXL features
rm: cannot remove '/usr/local/src/zabbix/frontends/php/zapix/assets': Directory not empty
rm: cannot remove '/usr/local/src/zabbix/frontends/php/zapix/css/bootstrap': Directory not empty
rm: cannot remove '/usr/local/src/zabbix/frontends/php/zapix/css/img': Directory not empty
rm: cannot remove '/usr/local/src/zabbix/frontends/php/zapix/js': Directory not empty
start zabbix-server error log like this.

**Comment by jangaraj** [comment]
https://github.com/monitoringartist/zabbix-xxl/issues/63

Overlay fs storage driver?

**Comment by yangswei** [comment]
i just copy docker-compose.yml then run "docker-compose up " on my virtual machine ，then "zabbix-server"and db-storage status is Exited and “docker logs xx ”get the  result as above..  but there are no probleon on my cloud host - -

**Comment by jangaraj** [comment]
Pls provide output from the command: 
```
docker info
```

**Comment by yangswei** [comment]
![image](https://user-images.githubusercontent.com/26788046/27811869-363462d8-609d-11e7-96c5-63e40a72fe33.png)
thanks ~

**Comment by jangaraj** [comment]
Your storage driver is overlay, so problem is not related to this project. The easiest solution is to change storage driver.  See Docker documentation how to change it. More info about issue: https://github.com/monitoringartist/zabbix-xxl/issues?utf8=%E2%9C%93&q=is%3Aissue%20overlay

**Comment by yangswei** [comment]
Thank you very much ~
