### ISSUE TITLE
Multiple Vulnerabilities in PHP 5.6.30

### ISSUE THREAD

**Issue by kujiy** [zabbix/zabbix-community-docker#92]
Thank you for sharing your excellent product always!

Could you rebuild your image on docker hub? [Remi's repository](https://rpms.remirepo.net/enterprise/7/php56/x86_64/repoview/)  seems to have provided the latest php 5.6.31.

> https://www.cisecurity.org/advisory/multiple-vulnerabilities-in-php-could-allow-for-arbitrary-code-execution-13/

**Comment by jangaraj** [comment]
All images have been rebuilt. Pull current version from the docker hub:
```
[root@dockerhost ~]# docker pull monitoringartist/zabbix-xxl:latest
latest: Pulling from monitoringartist/zabbix-xxl
Digest: sha256:7bf4fba548dafa757917dab9b20428b6bc730845c70f76cc4c4049eb8557a873
Status: Image is up to date for monitoringartist/zabbix-xxl:latest
[root@dockerhost ~]# docker run --rm -ti monitoringartist/zabbix-xxl:latest php -v
PHP 5.6.31 (cli) (built: Jul  6 2017 08:06:11)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies
```

**Comment by kujiy** [comment]
Thabk you! @jangaraj
