### ISSUE TITLE
zabbix-server return wrong item value - zbx_popen(): executing script

### ISSUE THREAD

**Issue by eberladin** [zabbix/zabbix-community-docker#93]
Hi !

I have issue running your "zabbix-server" container.

`[root@zabbix-server etc]# 	
    92:20170718:085131.702 zbx_popen(): executing script
1`

The script return value 0/1 - but **zabbix-server** return an extra _string zbx_popen(): executing_ script.

when i run same item on zabbix_agent - it works fine.
`sudo -u zabbix zabbix_agentd -c /etc/zabbix/zabbix_agentd.conf -t sipp.check_options[8.8.8.8]
sipp.check_options[8.8.8.8]                   [t|1]'

and return value 0 or 1

When i run that script from console it's OK:
**[root@zabbix-agent-sipp scripts]# sudo -u zabbix ./sip_opt_chk.sh 8.8.8.8
1**

Seems it's a bug - https://stackoverflow.com/questions/43976700/zabbix-discovery-with-external-check-json

This is bug. When DebugLevel is more than 3 Zabbix mix part of the debug output with the value data. Something like zbx_popen(): executing script. Solution to reduce DebugLevel to 3 or lower, and wait until ZBX-12195 will be fixed.

Can you add ENV Variable regarding ZS DebugLevel ? 
Or use latest 3.4 ZS in build ?

Regards, Ewgeniy

**Comment by jangaraj** [comment]
You can configure all zabbix server settings. Just add prefix ZS_. So please use env variable `ZS_DebugLevel` to set proper debug level.

**Comment by eberladin** [comment]
Thanks for the answer, but issue still exist:
just tried -     
environment:
      - ZS_DebugLevel=1

zabbix_server still return an extra value from ActiveCheck: zbx_popen(): executing script.
1

So - actually should be returned only "1" - last character.

**Comment by jangaraj** [comment]
You need to recreate container (= delete container and start new container) to apply that setting.

**Comment by eberladin** [comment]
it's done:

 docker-compose stop
Stopping zabbix_zabbix-server_1 ... done
Stopping zabbix_zabbix-agent-sipp_1 ... done
Stopping zabbix_zabbix-db_1 ... done
root@voip-zabbix:/docker/zabbix# 
root@voip-zabbix:/docker/zabbix# docker-compose rm zabbix-server
Going to remove zabbix_zabbix-server_1
Are you sure? [yN] y
Removing zabbix_zabbix-server_1 ... done
root@voip-zabbix:/docker/zabbix# docker-compose up -d --force-recreate --build
Building zabbix-agent-sipp
Step 1/7 : FROM centos:centos7
 ---> 36540f359ca3
Step 2/7 : RUN rpm -ivh http://repo.zabbix.com/zabbix/3.2/rhel/7/x86_64/zabbix-release-3.2-1.el7.noarch.rpm


......


docker-compose ps
           Name                         Command               State                                Ports                               
--------------------------------------------------------------------------------------------------------------------------------------
zabbix_zabbix-agent-sipp_1   /bin/sh -c sudo -u zabbix  ...   Up                                                                       
zabbix_zabbix-db_1           /run.sh                          Up      3306/tcp                                                         
zabbix_zabbix-server_1       /config/bootstrap.sh             Up      0.0.0.0:10051->10051/tcp, 10052/tcp, 162/udp, 0.0.0.0:80->80/tcp
