### ISSUE TITLE
Can't access Zabbix web interface

### ISSUE THREAD

**Issue by i-am-nut** [zabbix/zabbix-community-docker#95]
All of a sudden i can't access Zabbix web-interface anymore.

When i try to access the web it just time out.

I've already updated both `zabbix-xxl` and `zabbix-db-mariadb` image, but it didn't solve.

Docker log shows the following repetetly:

```
2017-08-24 19:13:19,600 DEBG 'zabbix-server' stdout output:
   397:20170824:191319.600 cannot send list of active checks to "127.0.0.1": host [Zabbix Server] not found

2017-08-24 19:13:19,600 DEBG 'zabbix-agent' stdout output:
   384:20170824:191319.600 no active checks on server [127.0.0.1:10051]: host [Zabbix Server] not found

``` 

and logs into containers only anaconda had anything but useless.

Any thoughts?

**Comment by jangaraj** [comment]
Increase Zabbix debug level, test nginx in the container with curl, test your networking, ....
I'm closing this request because it looks like a request for support - it's not clear that's image issue.
