### ISSUE TITLE
Zabbix 3.4

### ISSUE THREAD

**Issue by sonanchenko** [zabbix/zabbix-community-docker#96]
Hi Jan,

What about new version?

Are you going to release docker image with new release?

**Comment by jangaraj** [comment]
Yes, there is branch dockbix https://github.com/monitoringartist/zabbix-xxl/tree/dockbix, which is prepared for 3.4 version. README there must be updated. Image will be renamed to `monitoringartist/dockbix-xxl` due to problem with trademarks

**Comment by sonanchenko** [comment]
hello @jangaraj 

just to be on the same page with you,
is it ready for production?
Can I just update my 3.2 to 3.4 (leaving settings in place) just choosing "zabbix-xxl:dockbix" tag instead of 
"zabbix-xxl:latest" ?

Or when we can expect 3.4 as a main one for this image?

**Comment by jangaraj** [comment]
Done:
https://github.com/monitoringartist/dockbix-xxl/
https://hub.docker.com/r/monitoringartist/dockbix-xxl/tags/

Don't forget to backup your Zabbix DB before any update. Zabbix forum has a few discussions about 3.4 DB upgrade issues.

Main news for `monitoringartist/dockbix-xxl` image: Zabbix 3.4, PHP 7.
